[hololens]
package = "holo/lens-sencha-package"

[hololens.sencha]
pkg = "scienceleadership-interims-admin"

[hololens.input]
root = "sencha-workspace"
files = [
    "packages/scienceleadership-interims-admin/**",
    "ext/**",
    "workspace.json",
]

[hololens.output]
root = "webapp-plugin-builds/scienceleadership-interims-admin"
merge = "replace"