[holomapping]
files = [
    "*/**",
    "sencha-workspace/packages/**",
    "sencha-workspace/SlateStandardsBasedGradingTeacher/**",
    "!sencha-workspace/workspace.json",

    "!php-config/Git.config.d/"
]
